version: "3.8"

services:
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    container_name: web-client
    networks:
      - app-network
    ports:
      - "3001:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    networks:
      - app-network
    ports:
      - "3002:3000"

networks:
  app-network:
    driver: bridge
