version: "3.8"

services:
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    container_name: web-client
    networks:
      - app-network
    ports:
      - "3001:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    networks:
      - app-network
    ports:
      - "3002:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://myuser:mypassword@mongo:27017/mydb?authSource=admin

  mongo:
    image: mongo:8
    container_name: mongo
    restart: always
    networks:
      - app-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
